builds:
  - env:
      - GO15VENDOREXPERIMENT=1
      - GO111MODULE=off
    main: ./cmd/secretsfs
    goos:
      - linux
    goarch:
      - amd64
archives:
- replacements:
    linux: Linux
    amd64: x86_64
  files:
    - 'README.md'
    - 'example/*'
    - 'docs/*'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  - id: secretsfs
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: https://github.com/muryoutaisuu
    homepage: https://github.com/muryoutaisuu/secretsfs
    license: New BSD License
    maintainer: https://github.com/muryoutaisuu
    description: Access your secrets like passwords without a client directly from your filesystem with a simple cat call!
    formats:
      - rpm
    files:
      "example/secretsfs-logrotate.conf": "/etc/logrotate.d/secretsfs"
      "example/secretsfs.service": "/etc/systemd/system/secretsfs.service"
      "example/secretsfs-rsyslog.conf": "/etc/rsyslog.d/secretsfs.conf"
    empty_folders:
      - /etc/secretsfs
      - /etc/secretsfs/templates
    overrides:
      rpm:
        replacements:
          amd64: "x86_64"
        name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
