builds:
  - env:
    main: ./cmd/secretsfs
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-s -w -X main.Version={{.Version}}"
      - "-X main.BuildDate={{.Date}}"
archives:
- replacements:
    linux: Linux
    amd64: x86_64
  files:
    - 'README.md'
    - 'example/*'
    - 'docs/*'
    - 'LICENSE'
    - 'THIRDPARTYLICENSES'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  - id: secretsfs
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
    vendor: https://github.com/muryoutaisuu
    homepage: https://github.com/muryoutaisuu/secretsfs
    license: MIT License
    maintainer: https://github.com/muryoutaisuu
    description: Access your secrets like passwords without a client directly from your filesystem with a simple cat call!
    formats:
      - rpm
      - deb
    empty_folders:
      - /secretsfs
      - /etc/secretsfs
      - /etc/secretsfs/templates
    contents:
      - src: example/secretsfs-logrotate.conf
        dst: /etc/logrotate.d/secretsfs
      - src: example/secretsfs.service
        dst: /etc/systemd/system/secretsfs.service
      - src: example/secretsfs-rsyslog.conf
        dst: /etc/rsyslog.d/secretsfs.conf
      - src: example/secretsfs.yaml
        dst: /etc/secretsfs/secretsfs.yaml
        type: "config|noreplace"
    replacements:
      amd64: "x86_64"
release:
  github:
    owner: 'muryoutaisuu'
    name: 'secretsfs'
  prerelease: auto
