builds:
  - env:
    main: ./cmd/secretsfs
    goos:
      - linux
    goarch:
      - amd64
archives:
- replacements:
    linux: Linux
    amd64: x86_64
  files:
    - 'README.md'
    - 'example/*'
    - 'docs/*'
    - 'LICENSE'
    - 'THIRDPARTYLICENSES'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
source:
  enabled: true
  format: 'tar.gz'
nfpms:
  - id: secretsfs
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
    vendor: https://github.com/muryoutaisuu
    homepage: https://github.com/muryoutaisuu/secretsfs
    license: MIT License
    maintainer: https://github.com/muryoutaisuu
    description: Access your secrets like passwords without a client directly from your filesystem with a simple cat call!
    formats:
      - rpm
      - deb
    empty_folders:
      - /secretsfs
      - /etc/secretsfs
      - /etc/secretsfs/templates
    files:
      "example/secretsfs-logrotate.conf": "/etc/logrotate.d/secretsfs"
      "example/secretsfs.service": "/etc/systemd/system/secretsfs.service"
      "example/secretsfs-rsyslog.conf": "/etc/rsyslog.d/secretsfs.conf"
    config_files:
      "example/secretsfs.yaml": "/etc/secretsfs/secretsfs.yaml"
    replacements:
      amd64: "x86_64"
