# https://goreleaser.com/ci/
language: go

go:
  - "1.13.x"

addons:
  apt:
    packages:
    - rpm

env:
  matrix:
    - OS_TYPE=centos OS_VERSION=7

build:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash -s release --snapshot --rm-dist
    on:
      condition: $TRAVIS_OS_NAME = linux

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
