---
site_name: "secretsfs - Get Your Secrets via FUSE"
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - go
repo_url: https://github.com/muryoutaisuu/secretsfs
nav:
  - Home: 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Implementations': 'implementations.md'
  - 'Configuration': 'configuration.md'
  - 'Troubleshooting': 'troubleshooting.md'
  - 'Known Issues': 'known-issues.md'
